-- Copyright (C) 2024 Eccelerators GmbH
-- 
-- This code was generated by:
--
-- HxS Compiler v0.0.0-0000000
-- VHDL Extension for HxS v0.0.0-0000000
-- 
-- Further information at https://eccelerators.com/hxs
-- 
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

package PulseGeneratorPlainIfcPackage is

	type T_PulseGeneratorPlainIfcWishboneDown is
	record
		Adr : std_logic_vector(15 downto 0);
		Sel : std_logic_vector(3 downto 0);
		DatIn : std_logic_vector(31 downto 0);
		We : std_logic;
		Stb : std_logic;
		Cyc : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcWishboneUp is
	record
		DatOut : std_logic_vector(31 downto 0);
		Ack : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcTrace is
	record
		WishboneDown : T_PulseGeneratorPlainIfcWishboneDown;
		WishboneUp : T_PulseGeneratorPlainIfcWishboneUp;
		UnoccupiedAck : std_logic;
		TimeoutAck : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcPulseGeneratorPlainBlkDown is
	record
		Operation : std_logic_vector(1 downto 0);
		PulseWidthNs : std_logic_vector(23 downto 0);
		PulsePeriodNs : std_logic_vector(23 downto 0);
	end record;
	
	constant PULSEGENERATORPLAINBLK_BASE_ADDRESS : std_logic_vector(15 downto 0) := x"0000";
	constant PULSEGENERATORPLAINBLK_SIZE : std_logic_vector(15 downto 0) := x"0008";
	
	constant CONTROLREG_WIDTH : integer := 26;
	constant CONTROLREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0000" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant OPERATION_POSITION : integer := 24;
	constant OPERATION_WIDTH : integer := 2;
	constant OPERATION_MASK : std_logic_vector(31 downto 0) := x"03000000";
	constant CLEARED : std_logic_vector(1 downto 0) := "00";
	
	constant STOPPED : std_logic_vector(1 downto 0) := "01";
	
	constant RUNNING_ASTERISK_MASK : std_logic_vector(1 downto 0) := "10";
	
	type T_RUNNING_LIST is array(0 to 1) of std_logic_vector(1 downto 0);
	
	constant RUNNING_LIST : T_RUNNING_LIST := (
	   "10", "11");
	
	constant PULSEWIDTHNS_POSITION : integer := 0;
	constant PULSEWIDTHNS_WIDTH : integer := 24;
	constant PULSEWIDTHNS_MASK : std_logic_vector(31 downto 0) := x"00FFFFFF";
	
	constant PARAMETERREG_WIDTH : integer := 24;
	constant PARAMETERREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0004" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant PULSEPERIODNS_POSITION : integer := 0;
	constant PULSEPERIODNS_WIDTH : integer := 24;
	constant PULSEPERIODNS_MASK : std_logic_vector(31 downto 0) := x"00FFFFFF";
	
end;
