-- Copyright (C) 2025 Eccelerators GmbH
-- 
-- This code was generated by:
--
-- HxS Compiler 1.0.22-db393ac2
-- VHDL Extension for HxS 1.0.26-0b50ee5a
-- 
-- Further information at https://eccelerators.com/hxs
-- 
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

package PulseGeneratorPlainIfcUserPackage is
	
	type T_PulseGeneratorPlainIfcPulseGeneratorPlainBlkDown is
	record
		Operation : std_logic_vector(1 downto 0);
		PulsePeriodNs : std_logic_vector(31 downto 0);
		PulseWidthNs : std_logic_vector(31 downto 0);
	end record;
	
	constant PULSEGENERATORPLAINBLK_BASE_ADDRESS : std_logic_vector(15 downto 0) := x"0000";
	constant PULSEGENERATORPLAINBLK_SIZE : std_logic_vector(15 downto 0) := x"000C";
	
	constant CONTROLREG_WIDTH : integer := 32;
	constant CONTROLREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0000" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant OPERATION_POSITION : integer := 0;
	constant OPERATION_WIDTH : integer := 2;
	constant OPERATION_MASK : std_logic_vector(31 downto 0) := x"00000003";
	constant RUNNING : std_logic_vector(1 downto 0) := "11";
	constant CLEARED : std_logic_vector(1 downto 0) := "00";
	constant STOPPED : std_logic_vector(1 downto 0) := "01";
	
	constant PULSEPERIODREG_WIDTH : integer := 32;
	constant PULSEPERIODREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0004" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant PULSEPERIODNS_POSITION : integer := 0;
	constant PULSEPERIODNS_WIDTH : integer := 32;
	constant PULSEPERIODNS_MASK : std_logic_vector(31 downto 0) := x"FFFFFFFF";
	
	constant PULSEWIDTHREG_WIDTH : integer := 32;
	constant PULSEWIDTHREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0008" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant PULSEWIDTHNS_POSITION : integer := 0;
	constant PULSEWIDTHNS_WIDTH : integer := 32;
	constant PULSEWIDTHNS_MASK : std_logic_vector(31 downto 0) := x"FFFFFFFF";
	
	constant RST0_INIT : std_logic_vector(31 downto 0) := x"00000FA0";
	
	constant RST1_INIT : std_logic_vector(31 downto 0) := x"000005DC";
	
end;
