-- Copyright (C) 2025 Eccelerators GmbH
-- 
-- This code was generated by:
--
-- HxS Compiler 1.0.22-db393ac2
-- VHDL Extension for HxS 1.0.26-0b50ee5a
-- 
-- Further information at https://eccelerators.com/hxs
-- 
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;


package PulseGeneratorPlainIfcAvalonPackage is

	type T_PulseGeneratorPlainIfcAvalonDown is
	record
		Address : std_logic_vector(15 downto 0);
		ByteEnable : std_logic_vector(3 downto 0);
		Write : std_logic;
		WriteData : std_logic_vector(31 downto 0);
		Read : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcAvalonUp is
	record
		ReadData : std_logic_vector(31 downto 0);
		WaitRequest : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcAvalonTrace is
	record
		AvalonDown : T_PulseGeneratorPlainIfcAvalonDown;
		AvalonUp : T_PulseGeneratorPlainIfcAvalonUp;
		UnoccupiedAck : std_logic;
		TimeoutAck : std_logic;
	end record;

end;
