onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tbtop/Clk
add wave -noupdate /tbtop/Rst
add wave -noupdate /tbtop/executing_line
add wave -noupdate /tbtop/executing_file
add wave -noupdate /tbtop/marker
add wave -noupdate /tbtop/standard_test_error_count
add wave -noupdate -childformat {{/tbtop/signals_in.in_signal_2004 -radix decimal} {/tbtop/signals_in.in_signal_2005 -radix decimal} {/tbtop/signals_in.in_signal_2006 -radix decimal} {/tbtop/signals_in.in_signal_2007 -radix decimal} {/tbtop/signals_in.in_signal_2008 -radix decimal} {/tbtop/signals_in.in_signal_2009 -radix decimal} {/tbtop/signals_in.in_signal_2010 -radix decimal} {/tbtop/signals_in.in_signal_2011 -radix decimal} {/tbtop/signals_in.in_signal_2012 -radix decimal} {/tbtop/signals_in.in_signal_2013 -radix decimal}} -expand -subitemconfig {/tbtop/signals_in.in_signal_2004 {-radix decimal} /tbtop/signals_in.in_signal_2005 {-radix decimal} /tbtop/signals_in.in_signal_2006 {-radix decimal} /tbtop/signals_in.in_signal_2007 {-radix decimal} /tbtop/signals_in.in_signal_2008 {-radix decimal} /tbtop/signals_in.in_signal_2009 {-radix decimal} /tbtop/signals_in.in_signal_2010 {-radix decimal} /tbtop/signals_in.in_signal_2011 {-radix decimal} /tbtop/signals_in.in_signal_2012 {-radix decimal} /tbtop/signals_in.in_signal_2013 {-radix decimal}} /tbtop/signals_in
add wave -noupdate /tbtop/signals_out
add wave -noupdate /tbtop/bus_down
add wave -noupdate /tbtop/bus_up
add wave -noupdate /tbtop/InitPulseGeneratorPlain
add wave -noupdate /tbtop/Pulse
add wave -noupdate /tbtop/Failure
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/PulseGeneratorPlainAxi4LiteDown
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/PulseGeneratorPlainAxi4LiteUp
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/PulseGeneratorPlainAxi4LiteTrace
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/PulseGeneratorPlainBlkDown
add wave -noupdate -radix unsigned /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainUserLogic/CountNs
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainUserLogic/PulsePeriodNs
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainUserLogic/PulseWidthNs
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Clk
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Rst
add wave -noupdate -expand /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Axi4LiteDown
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Axi4LiteUp
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Axi4LiteAccess
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Trace
add wave -noupdate -expand /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkDown
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PreAxi4LiteUp
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PreAxi4LiteAccess
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/UnoccupiedAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/TimeoutAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadData
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadResp
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Read
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadAddressMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/ReadAddress
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/Write
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteAddrMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteAddress
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteData
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/WriteByteEnable
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkReadMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkReadAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkReadData
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkReadResp
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkWriteMatch
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/PulseGeneratorPlainBlkWriteAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreReadData
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreReadDataControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreOrReadDataControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreReadAckControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/ReadDiffControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreWriteAckControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/WriteDiffControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/WRegOperation
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/WRegPulseWidthNs
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreMatchReadControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreMatchWriteControlReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreReadDataParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreOrReadDataParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreReadAckParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/ReadDiffParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreWriteAckParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/WriteDiffParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/WRegPulsePeriodNs
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreMatchReadParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainBlk_PulseGeneratorPlainIfcAxi4Lite/PreMatchWriteParameterReg
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/Axi4LiteReadState
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/Axi4LiteWriteState
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/ReadTimeoutCounter
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/WriteTimeoutCounter
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/ReadUnoccupiedAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/WriteUnoccupiedAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/ReadTimeoutAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/WriteTimeoutAck
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/ReadProtect
add wave -noupdate /tbtop/g_tb_DutAxi4Lite/i_tbDutAxi4Lite/i_PulseGeneratorPlainAxi4LiteHxs/i_PulseGeneratorPlainIfcAxi4Lite/i_PulseGeneratorPlainIfcAxi4LiteBusController/WriteProtect
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3725000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 327
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {20585880 ps}
