/* Copyright (C) 2024 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler v0.0.0-0000000
   C Extension for HxS v0.0.0-0000000
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _PulseGeneratorPlainIfc_H
#define _PulseGeneratorPlainIfc_H



/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define PulseGeneratorPlainIfcAddressBusWidth 16
#define PulseGeneratorPlainIfcDataBusWidth 32

#define PulseGeneratorPlainBlkAddress 0x0000
#define PulseGeneratorPlainBlkSize 0x0008

#define ControlRegAddress (0x0000 + PulseGeneratorPlainBlkAddress)
#define ControlRegWidth 26

#define OperationMask 0x3000000
#define OperationPosition 24
#define OperationWidth 2
#define ClearedMVal 0x0000000
#define StoppedMVal 0x1000000
#define RunningMValAMask 0x2000000
#define RunningMValListSize 2
#define RunningMValList { \
    0x2000000, 0x3000000};
#define OperationBusResetMRstVal 0x0000000

#define PulseWidthNsMask 0x0FFFFFF
#define PulseWidthNsPosition 0
#define PulseWidthNsWidth 24
#define PulseWidthNsBusResetMRstVal 0x0000000

#define ParameterRegAddress (0x0004 + PulseGeneratorPlainBlkAddress)
#define ParameterRegWidth 24

#define PulsePeriodNsMask 0xFFFFFF
#define PulsePeriodNsPosition 0
#define PulsePeriodNsWidth 24
#define PulsePeriodNsBusResetMRstVal 0x000000

#endif
