/* Copyright (C) 2025 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler 1.0.22-db393ac2
   C Extension for HxS 1.0.26-97801b8b
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _PulseGeneratorPlainIfc_H
#define _PulseGeneratorPlainIfc_H



/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define PulseGeneratorPlainIfcAddressBusWidth 16
#define PulseGeneratorPlainIfcDataBusWidth 32

#define PulseGeneratorPlainBlkAddress 0x0000
#define PulseGeneratorPlainBlkSize 0x000C

#define ControlRegAddress (0x0000 + PulseGeneratorPlainBlkAddress)
#define ControlRegWidth 2

#define OperationMask 0x3
#define OperationPosition 0
#define OperationWidth 2
#define ClearedMVal 0x0
#define StoppedMVal 0x1
#define RunningMVal 0x3
#define OperationBusResetMRstVal 0x0

#define PulsePeriodRegAddress (0x0001 + PulseGeneratorPlainBlkAddress)
#define PulsePeriodRegWidth 32

#define PulsePeriodNsMask 0xFFFFFFFF
#define PulsePeriodNsPosition 0
#define PulsePeriodNsWidth 32
#define PulsePeriodNsBusResetMRstVal 0x00000000

#define PulseWidthRegAddress (0x0005 + PulseGeneratorPlainBlkAddress)
#define PulseWidthRegWidth 32

#define PulseWidthNsMask 0xFFFFFFFF
#define PulseWidthNsPosition 0
#define PulseWidthNsWidth 32
#define PulseWidthNsBusResetMRstVal 0x00000000

#endif
