# Copyright (C) 2025 Eccelerators GmbH
# 
# This code was generated by:
#
# HxS Compiler 1.0.22-db393ac2
# Python Extension for HxS 1.0.10-19866467
# 
# Further information at https://eccelerators.com/hxs
# 
# Changes to this file may cause incorrect behavior and will be lost if the
# code is regenerated.
	
	
# -----------------------------------------------------
# Addresses, widths, values and masks for direct access
# -----------------------------------------------------
PulseGeneratorPlainIfcAddressBusWidth = 16
PulseGeneratorPlainIfcDataBusWidth = 32

class PulseGeneratorPlainBlk:
    PulseGeneratorPlainBlkAddress = 0x0000 
    PulseGeneratorPlainBlkSize = 0x000C 

    @property
    def ControlRegAddress(self):
        return (0x0000 + self.PulseGeneratorPlainBlkAddress)

    ControlRegWidth = 2

    OperationMask = 0x3
    OperationPosition = 0
    OperationWidth = 2
    ClearedMVal = 0x0
    StoppedMVal = 0x1
    RunningMVal = 0x3
    OperationBusResetMRstVal = 0x0


    @property
    def PulsePeriodRegAddress(self):
        return (0x0001 + self.PulseGeneratorPlainBlkAddress)

    PulsePeriodRegWidth = 32

    PulsePeriodNsMask = 0xFFFFFFFF
    PulsePeriodNsPosition = 0
    PulsePeriodNsWidth = 32
    PulsePeriodNsBusResetMRstVal = 0x00000000


    @property
    def PulseWidthRegAddress(self):
        return (0x0005 + self.PulseGeneratorPlainBlkAddress)

    PulseWidthRegWidth = 32

    PulseWidthNsMask = 0xFFFFFFFF
    PulseWidthNsPosition = 0
    PulseWidthNsWidth = 32
    PulseWidthNsBusResetMRstVal = 0x00000000
