-- Copyright (C) 2024 Eccelerators GmbH
-- 
-- This code was generated by:
--
-- HxS Compiler v0.0.0-0000000
-- VHDL Extension for HxS v0.0.0-0000000
-- 
-- Further information at https://eccelerators.com/hxs
-- 
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

package PulseGeneratorPlainIfcPackage is

	type T_PulseGeneratorPlainIfcWishboneDown is
	record
		Adr : std_logic_vector(15 downto 0);
		Sel : std_logic_vector(3 downto 0);
		DatIn : std_logic_vector(31 downto 0);
		We : std_logic;
		Stb : std_logic;
		Cyc : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcWishboneUp is
	record
		DatOut : std_logic_vector(31 downto 0);
		Ack : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcTrace is
	record
		WishboneDown : T_PulseGeneratorPlainIfcWishboneDown;
		WishboneUp : T_PulseGeneratorPlainIfcWishboneUp;
		UnoccupiedAck : std_logic;
		TimeoutAck : std_logic;
	end record;
	
	type T_PulseGeneratorPlainIfcPulseGeneratorPlainBlkDown is
	record
		Operation : std_logic;
		PulseWidthNs : std_logic_vector(23 downto 0);
	end record;
	
	constant PULSEGENERATORPLAINBLK_BASE_ADDRESS : std_logic_vector(15 downto 0) := x"0000";
	constant PULSEGENERATORPLAINBLK_SIZE : std_logic_vector(15 downto 0) := x"0004";
	
	constant CONTROLREG_WIDTH : integer := 25;
	constant CONTROLREG_ADDRESS : std_logic_vector(15 downto 0) := std_logic_vector(x"0000" + unsigned(PULSEGENERATORPLAINBLK_BASE_ADDRESS));
	
	constant OPERATION_POSITION : integer := 24;
	constant OPERATION_WIDTH : integer := 1;
	constant OPERATION_MASK : std_logic_vector(31 downto 0) := x"01000000";
	constant OFF : std_logic := '0';
	constant ON : std_logic := '1';
	
	constant PULSEWIDTHNS_POSITION : integer := 0;
	constant PULSEWIDTHNS_WIDTH : integer := 24;
	constant PULSEWIDTHNS_MASK : std_logic_vector(31 downto 0) := x"00FFFFFF";
	
end;
